(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(TeX-PDF-mode t)
 '(TeX-save-query nil)
 '(TeX-source-correlate-method (quote synctex))
 '(TeX-source-correlate-mode t)
 '(TeX-source-correlate-start-server t)
 '(TeX-view-program-list (quote (("Skim" "open %o"))))
 '(TeX-view-program-selection (quote ((output-pdf "Skim") (output-dvi "xdvi") (output-pdf "Evince") (output-html "xdg-open"))))
 '(ac-delay 0.3)
 '(ac-ignore-case nil)
 '(ac-show-menu-immediately-on-auto-complete nil)
 '(ac-stop-words (quote ("/" ";")))
 '(ack-and-a-half-executable "/usr/local/bin/ack")
 '(ack-and-a-half-mode-extension-alist (quote ((js2-mode "js" "json" "rb") (js-mode "js" "json" "rb"))))
 '(ack-executable "/usr/local/bin/ack")
 '(appmenu-mode nil)
 '(auth-sources (quote ("~/.authinfo" "~/.authinfo.gpg")))
 '(bell-volume 0)
 '(block-comment-end nil t)
 '(bm-buffer-persistence t)
 '(bm-electric-show t)
 '(bm-recenter t)
 '(bmkp-auto-light-when-set (quote autonamed-bookmark))
 '(bmkp-last-as-first-bookmark-file "~/.emacs.d/bookmarks")
 '(c-basic-offset 4)
 '(c-comment-continuation-stars "* ")
 '(c-comment-only-line-offset 0)
 '(canlock-password "1085e8558dcb0236dbd9c1926f175176486526c1")
 '(case-fold-search t)
 '(column-number-mode t)
 '(comment-line-break-function (quote indent-new-comment-line) t)
 '(comment-multi-line t)
 '(comment-start "/** " t)
 '(comment-start-skip "/\\*\\*" t)
 '(company-auto-complete t)
 '(compilation-ask-about-save nil)
 '(compilation-auto-jump-to-first-error t)
 '(compilation-process-setup-function nil t)
 '(compilation-scroll-output t)
 '(compilation-skip-to-next-location nil t)
 '(compilation-window-height 12)
 '(compile-auto-highlight t)
 '(create-lockfiles nil)
 '(cua-delete-selection t)
 '(cua-enable-cua-keys nil)
 '(cua-mode t nil (cua-base))
 '(current-language-environment "Latin-2")
 '(cursor-in-non-selected-windows nil)
 '(cycbuf-attributes-list (quote (("M" 1 left cycbuf-get-modified-string) ("R" 2 left cycbuf-get-readonly-string) ("Mode" 12 left cycbuf-get-mode-name) ("" 2 left "  ") ("" 1 left " ") ("Buffer" cycbuf-get-name-length left cycbuf-get-name) ("" 2 left "  "))))
 '(cycbuf-buffer-sort-function (quote cycbuf-sort-by-recency))
 '(cycbuf-clear-delay 1.2)
 '(cycbuf-dont-show-regexp (quote ("^ " "^\\*cycbuf\\*$" "^\\*")))
 '(cycbuf-max-window-height 4)
 '(default-frame-alist (quote ((top . 50) (left . 50) (width . 100) (height . 40))))
 '(default-indicate-buffer-boundaries (quote left) t)
 '(default-input-method "latin-2-prefix")
 '(default-justification (quote left))
 '(desktop-base-file-name ".emacs.desktop")
 '(desktop-buffers-not-to-save "")
 '(desktop-file-name-format (quote absolute))
 '(desktop-files-not-to-save "^$")
 '(desktop-path (quote ("." "~/.emacs.d/" "~" "~/.notes")))
 '(desktop-save nil)
 '(desktop-save-mode nil)
 '(dired-listing-switches "-alo")
 '(epg-debug t)
 '(epg-gpg-program "/usr/local/MacGPG2/bin/gpg2")
 '(epg-gpgsm-program "/usr/local/MacGPG2/bin/gpgsm")
 '(erc-nick "grabarz")
 '(feature-cucumber-command "cucumber --format pretty -s {options} {feature}")
 '(feature-use-rvm t)
 '(file-cache-filter-regexps (quote ("~$" "\\.o$" "\\.exe$" "\\.a$" "\\.elc$" ",v$" "\\.output$" "\\.$" "#$" "\\.class$" "tmp/")))
 '(focus-follows-mouse nil)
 '(font-lock-beginning-of-syntax-function nil t)
 '(font-lock-keywords-case-fold-search nil t)
 '(font-lock-keywords-only nil t)
 '(font-lock-mark-block-function nil t)
 '(font-lock-maximum-decoration t)
 '(gh-api-v3-authenticator (quote gh-password-authenticator))
 '(global-ace-isearch-mode t)
 '(global-font-lock-mode t nil (font-lock))
 '(global-visual-line-mode nil)
 '(gnus-asynchronous nil)
 '(gnus-make-format-preserve-properties nil)
 '(gnus-parameter-large-newsgroup-initial 700)
 '(gnus-use-correct-string-widths t)
 '(golden-ratio-exclude-buffer-names (quote ("*helm imenu*" "*helm etags*" "*Ediff Control Panel*")))
 '(golden-ratio-exclude-modes (quote ("helm-mode" "gnus-summary-mode" "gnus-group-mode" "gnus-article-mode")))
 '(helm-completing-read-handlers-alist (quote ((describe-function . helm-completing-read-symbols) (describe-variable . helm-completing-read-symbols) (debug-on-entry . helm-completing-read-symbols) (find-function . helm-completing-read-symbols) (find-tag . helm-completing-read-with-cands-in-buffer) (ffap-alternate-file) (tmm-menubar) (cycbuf-switch-to-next-buffer))))
 '(helm-truncate-lines t)
 '(hscroll-step 1)
 '(ibuffer-display-summary nil)
 '(ibuffer-never-show-predicates (quote (".*indent-buffer" ".*nxhtml-mode.*" ".newsrc*" "*nnimap*" "*gnus trace*" "*fsm-debug*" "*tramp/")) nil (ibuf-ext))
 '(imenu-case-fold-search t t)
 '(imenu-sort-function (quote imenu--sort-by-name))
 '(indent-tabs-mode t)
 '(inhibit-startup-screen t)
 '(js2-auto-indent-p t)
 '(js2-cleanup-whitespace t)
 '(js2-enter-indents-newline t)
 '(js2-global-externs (quote ("$" "Ext" (\, "describe") (\, "it") (\, "require"))))
 '(js2-include-browser-externs t)
 '(js2-include-node-externs t)
 '(js2-mirror-mode nil)
 '(lazy-lock-defer-time 0.1)
 '(ls-lisp-dirs-first t)
 '(ls-lisp-ignore-case t)
 '(ls-lisp-use-insert-directory-program nil)
 '(magit-process-connection-type nil)
 '(makefile-electric-keys t)
 '(menu-bar-mode nil)
 '(minibuffer-max-depth nil)
 '(mouse-drag-copy-region nil)
 '(mouse-yank-at-point nil)
 '(normal-erase-is-backspace t)
 '(org-agenda-current-time-string #("<- [ NOW ]" 0 2 (org-heading t)))
 '(org-agenda-tags-column -80)
 '(org-email-link-description-format "Email %c: %s")
 '(org-tags-column -90)
 '(paren-dont-touch-blink t)
 '(popcmp-completion-style (quote anything))
 '(popcmp-group-alternatives nil)
 '(popcmp-short-help-beside-alts t)
 '(prelude-theme (quote ample-zen-theme))
 '(projectile-enable-idle-timer t)
 '(rebind-keys-mode nil)
 '(ring-bell-function (quote ignore) t)
 '(same-window-regexps (quote ("\\*magit.*")))
 '(scss-compile-at-save nil t)
 '(show-smartparens-global-mode t)
 '(size-indication-mode t)
 '(smartparens-global-strict-mode t)
 '(sp-autoescape-string-quote nil)
 '(sp-base-key-bindings (quote sp))
 '(sp-navigate-close-if-unbalanced t)
 '(swbuff-clear-delay 0.5)
 '(tab-width 4)
 '(tabkey2-choose-next-on-error nil)
 '(tabkey2-mode nil)
 '(tool-bar-mode nil)
 '(visible-bell nil)
 '(yas-prompt-functions (quote (yas-completing-prompt yas-ido-prompt yas-no-prompt)))
 '(yas-wrap-around-region t)
 '(zencoding-preview-default nil))

(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(bmkp-desktop ((t (:foreground "orange" :background "#2d2d2d"))))
 '(comint-highlight-input ((t (:underline nil :weight bold))))
 '(comint-highlight-prompt ((t (:inherit minibuffer-prompt :underline nil))))
 '(compilation-column-number ((t (:inherit font-lock-doc-face :underline nil))))
 '(compilation-error ((t (:inherit error :underline nil :slant italic))))
 '(compilation-warning ((t (:inherit warning :underline nil))))
 '(cperl-array-face ((t (:background "gray30" :foreground "orange"))))
 '(cperl-hash-face ((t (:background "gray30" :foreground "yellow3"))))
 '(cycbuf-current-face ((t (:background "gray" :foreground "black" :weight bold))))
 '(diff-hunk-header ((t (:background "#111"))))
 '(diff-indicator-added ((t (:foreground "DarkGreen"))))
 '(diff-indicator-removed ((t (:foreground "DarkRed"))))
 '(dired-marked ((t (:foreground "Yellow"))))
 '(diredp-file-name ((t (:foreground "#eee"))) t)
 '(diredp-file-suffix ((t (:foreground "#ddd"))) t)
 '(diredp-number ((t (:foreground "#eee"))) t)
 '(diredp-read-priv ((t nil)) t)
 '(diredp-write-priv ((t nil)) t)
 '(face-1 ((t (:foreground "grey30"))))
 '(face-2 ((t (:foreground "white" :weight bold :font "Ubuntu Mono" :height 140))))
 '(face-3 ((t (:weight normal))))
 '(face-4 ((t (:foreground "orange" :font "Ubuntu Mono" :height 140))))
 '(face-5 ((t (:foreground "grey40"))))
 '(face-6 ((t (:foreground "red"))))
 '(golden-ratio-exclude-buffer-names (quote ("*helm imenu*" "*helm etags*" "*Ediff Control Panel*" "*bm-bookmarks*")))
 '(helm-candidate-number ((t (:foreground "#888" :underline nil :weight normal))))
 '(helm-ff-directory ((t (:foreground "LightSalmon" :underline nil :weight bold))))
 '(helm-ff-file ((t (:foreground "CadetBlue" :underline nil :weight normal))))
 '(helm-ff-prefix ((t (:foreground "#888" :background "#333"))))
 '(helm-selection ((t (:background "#333" :foreground "#aaa"))))
 '(helm-source-header ((t (:background "#1d1d1d" :foreground "#888" :underline t :weight normal))))
 '(highline-face ((t (:background "#666"))))
 '(magit-blame-culprit ((t (:foreground "LightGoldenrod2" :background "#333" :box (:line-width -1 :style released-button)))))
 '(magit-blame-header ((t (:background "#333" :box (:line-width -1 :style released-button)))))
 '(magit-blame-sha1 ((t (:foreground "cyan" :background "#333" :box (:line-width -1 :style released-button)))))
 '(magit-blame-subject ((t (:foreground "DarkGoldenrod2" :background "#333" :box (:line-width -1 :style released-button)))))
 '(magit-blame-time ((t (:foreground "DarkGoldenrod" :background "#333" :box (:line-width -1 :style released-button)))))
 '(magit-diff-add ((t (:foreground "green"))))
 '(magit-diff-del ((t (:foreground "red"))))
 '(magit-diff-hunk-header ((t (:background "#333" :foreground "cyan"))))
 '(org-document-info ((t (:height 0.9 :family "Tahoma" :weight bold))))
 '(org-document-title ((t (:height 0.9 :family "Tahoma" :weight bold))))
 '(twittering-uri-face ((t (:foreground "gray70" :underline nil))))
 '(twittering-username-face ((t (:foreground "LightSalmon" :underline nil :weight bold)))))
